change-husky-yarn

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -10,24 +10,24 @@ NC='\033[0m'
 
 echo "\n 🚧🏗️  ${BOLD}Checking format, lint and types in your project before committing${NC}"
 
-npm run format
+yarn format
 
 # Check Prettier standards
-npm run check-format ||
+yarn check-format ||
 (
-    echo "\n ❌🟨 Prettier Check ${RED}Failed${NC}. 🟨❌\n Run ${BLUE}npm run format${NC}, add changes and try commit again.\n";
+    echo "\n ❌🟨 Prettier Check ${RED}Failed${NC}. 🟨❌\n Run ${BLUE}yarn format${NC}, add changes and try commit again.\n";
     false;
 )
 
 # Check ESLint Standards
-npm run check-lint ||
+yarn check-lint ||
 (
     echo "\n ❌🟪 ESLint Check ${RED}Failed${NC}. 🟪❌\n Make the required changes listed above, add changes and try to commit again.\n"
     false;
 )
 
 # Check tsconfig standards
-npm run check-types ||
+yarn check-types ||
 (
     echo "\n ❌🟦 Type check ${RED}Failed${NC}. 🟦❌\n Make the changes required above.\n"
     false;
@@ -36,7 +36,7 @@ npm run check-types ||
 # If everything passes... Now we can build
 echo "🔥🚀 ${BOLD}All passed... Now we can build.${NC} 🚀🔥"
 
-npm run build ||
+yarn build ||
 (
     echo "\n ❌🟩 Next build ${RED}Failed${NC}. 🟩❌\n View the errors above to see why.\n"
     false;
